import { QuestionPlugin } from "@/types/plugin";

export const iso14001Plugin: QuestionPlugin = {
  id: "iso-14001",
  name: "ISO 14001",
  version: "1.0.0",
  standard: "ISO 14001",
  description:
    "ISO 14001 Environmental Management System (EMS) Compliance Metrics",
  category: "Environmental",
  questions: [
    {
      id: "iso-14001-ems",
      text: "Does your organization have a documented Environmental Management System (EMS) in place?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-4.1",
    },
    {
      id: "iso-14001-policy",
      text: "Has your organization established and communicated an environmental policy?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-5.2",
    },
    {
      id: "iso-14001-energy",
      text: "Total energy consumption from all sources",
      type: "number",
      unit: "Joules",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-renewable-energy",
      text: "Percentage of total energy consumption derived from renewable sources",
      type: "number",
      unit: "Percentage (%)",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-water",
      text: "Total water consumption by the organization",
      type: "number",
      unit: "Cubic meters",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-water-reuse",
      text: "Percentage of water reused or recycled",
      type: "number",
      unit: "Percentage (%)",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-emissions-co2",
      text: "Total direct greenhouse gas (GHG) emissions (Scope 1)",
      type: "number",
      unit: "Metric Tonnes CO₂",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-emissions-scope2",
      text: "Total indirect greenhouse gas (GHG) emissions (Scope 2)",
      type: "number",
      unit: "Metric Tonnes CO₂",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-emissions-other",
      text: "Total emissions of NOx, SOx, and other significant air pollutants",
      type: "number",
      unit: "Metric Tonnes",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-waste",
      text: "Total hazardous waste generated",
      type: "number",
      unit: "Metric Tonnes",
      code: "ISO 14001-8.1",
    },
    {
      id: "iso-14001-waste-recycling",
      text: "Percentage of total waste that is recycled or reused",
      type: "number",
      unit: "Percentage (%)",
      code: "ISO 14001-8.1",
    },
    {
      id: "iso-14001-chemical-use",
      text: "Does your organization track and manage the use of hazardous chemicals?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-biodiversity",
      text: "Has your organization taken steps to protect biodiversity and ecosystems?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-compliance",
      text: "Has the organization faced any environmental legal non-compliance cases in the past reporting period?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-9.1.2",
    },
    {
      id: "iso-14001-audit",
      text: "Has the organization conducted an internal environmental audit in the last year?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-9.2",
    },
    {
      id: "iso-14001-risk-assessment",
      text: "Has the organization conducted an environmental risk assessment?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-6.1.2",
    },
    {
      id: "iso-14001-emergency-plan",
      text: "Does the organization have an environmental emergency response plan?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-8.2",
    },
    {
      id: "iso-14001-incident-reporting",
      text: "Number of environmental incidents reported in the past year",
      type: "number",
      unit: "Count",
      code: "ISO 14001-9.1.2",
    },
    {
      id: "iso-14001-legal-violations",
      text: "Total monetary fines incurred due to environmental violations",
      type: "number",
      unit: "Presentation currency",
      code: "ISO 14001-9.1.2",
    },
    {
      id: "iso-14001-training",
      text: "Percentage of employees who have received environmental management training",
      type: "number",
      unit: "Percentage (%)",
      code: "ISO 14001-7.3",
    },
    {
      id: "iso-14001-improvement",
      text: "Number of corrective and preventive actions taken as part of continuous improvement efforts",
      type: "number",
      unit: "Count",
      code: "ISO 14001-10.2",
    },
    {
      id: "iso-14001-supply-chain",
      text: "Does your organization assess the environmental impact of its supply chain?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-8.1",
    },
    {
      id: "iso-14001-stakeholders",
      text: "Has the organization engaged stakeholders in environmental decision-making?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-4.2",
    },
    {
      id: "iso-14001-reporting",
      text: "Does your organization publish an annual environmental sustainability report?",
      type: "boolean",
      unit: "n/a",
      code: "ISO 14001-9.3",
    },
  ],
  metadata: {
    author: "ISO Standards Board",
    website: "https://www.iso.org/iso-14001-environmental-management.html",
  },
};
